name: Deploy Flask App

on:
  push:
    branches:
    - main

env:
  HEALTHCHECK_URL: http://174.129.134.54:5000

jobs:
  build-test-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: python -m unittest test_app.py

      - name: Kill existing Flask processes (if any)
        run: |
          pkill -f app.py || true

      - name: Start Flask App
        run: |
          nohup python app.py > flask.log 2>&1 &
        shell: bash

  health:
    needs: build-test-deploy
    runs-on: self-hosted

    steps:
      - name: Health Check
        run: |
          echo "Checking health at $HEALTHCHECK_URL"
          for i in {1..10}; do
            status_code=$(curl -s -o /dev/null -w "%{http_code}" "$HEALTHCHECK_URL")
            if [ "$status_code" == "200" ]; then
              echo "✅ Health check passed"
              exit 0
            else
              echo "Waiting for service... (Status: $status_code)"
              sleep 5
            fi
          done
          echo "❌ Health check failed.."
          exit 1
